version: '3'
volumes:
  bundle:
services:
  db:
    image: postgres:9.4.4
    ports:
      - "55431:5432"
  web:
    build: .
    image: onproject:latest
    command: /sbin/my_init --enable-insecure-key #enable insecure key for dev
    volumes:
      - .:/home/app/onproject
      - bundle:/home/app/bundle
    depends_on:
      - db
    ports:
      - "3000:80"
      - "2221:22"
    environment:
      RAILS_ENV: development
      PASSENGER_APP_ENV: development
      BUNDLE_PATH: /home/app/bundle
      FB_APP_ID: 1024153647670036
