pg_defaults: &pg_defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password:
  host: <%= ENV['DB_HOST'] %>
  template: template0

test:
  <<: *pg_defaults
  database: onproject_test
  port: 5432

development:
  <<: *pg_defaults
  database: onproject_dev

production:
  adapter:  postgresql
  host:     ec2-107-20-193-74.compute-1.amazonaws.com
  encoding: unicode
  database: d4bmkirb1bm50m
  pool:     5
  username: gmcieqhhbbrzph
  password: aad9b2cfd3a37cd71286f5864376abebe0d4c0b3d2c2e46091026eaf7824528b
  template: template0
