# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: OnProject_development
  pool:     5
  username: postgres
  password: postgres
  template: template0

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: OnProject_test
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  host:     ec2-107-20-195-181.compute-1.amazonaws.com
  encoding: unicode
  database: de6kgn6at5hvpe
  pool:     5
  username: gbqhibghtphgni
  password: 52d439f0f2b2f4840e147fc9d0d2159f4a438ab5f0483acef65dbf15842e4976
  template: template0
